export default [
  {
    id: 2,
    book: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    cover: "https://m.media-amazon.com/images/I/816kmbEXrJL._AC_UL320_.jpg",
    tags: [
      "great gatsby ",
      "nick carraway ",
      "high school ",
      "american dream ",
      "new york ",
      "long island ",
      "scott fitzgerald ",
      "jay gatsby ",
      "west egg ",
      "american classic ",
      "daisy buchanan ",
      "great book ",
      "children corner ",
      "writing style ",
      "husband tom ",
      "jordan baker ",
      "time around ",
      "old sport ",
      "good read ",
      "love story",
    ],
    description: "",
  },
  {
    id: 3,
    book: "In Search of Lost Time",
    author: "Marcel Proust",
    cover: "https://m.media-amazon.com/images/I/81yo44UiIUL._AC_UL320_.jpg",
    tags: [],
    description: "",
  },
  {
    id: 4,
    book: "Ulysses*",
    author: "James Joyce",
    cover: "https://m.media-amazon.com/images/I/81zh6m3UR6L._AC_UL320_.jpg",
    tags: [],
  },
  {
    id: 5,
    book: "Dubliners*",
    author: "James Joyce",
    cover: "https://m.media-amazon.com/images/I/41lpHDg6b8L._AC_UL320_.jpg",
    tags: [],
    description: "",
  },
  {
    id: 6,
    book: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    cover: "https://images-na.ssl-images-amazon.com/images/I/61pMvyfWphL._SX369_BO1,204,203,200_.jpg",
    tags: [
      "years of solitude ",
      "garcia marquez ",
      "buendia family ",
      "magical realism ",
      "gabriel garcia ",
      "latin american ",
      "nobel prize ",
      "jose arcadio ",
      "magical realism ",
      "family tree ",
      "latin america ",
      "ever read ",
      "south american ",
      "town of macondo ",
      "colonel aureliano ",
      "rise and fall ",
      "banana company ",
      "garcía márquez ",
      "keep track ",
      "years ago",
    ],
    description: "",
  },
  {
    id: 7,
    book: "The Sound and the Fury",
    author: "William Faulkner",
    cover: "https://images-na.ssl-images-amazon.com/images/I/51d9xpOKZnL._SX300_BO1,204,203,200_.jpg",
    tags: [
      "sound and the fury ",
      "cliff notes ",
      "compson family ",
      "stream of consciousness ",
      "william faulkner ",
      "year old ",
      "point of view ",
      "sister caddy ",
      "ever read ",
      "tale told ",
      "signifying nothing ",
      "told by an idiot ",
      "section is told ",
      "lay dying ",
      "absalom absalom ",
      "ever written ",
      "mentally retarded ",
      "nobel prize ",
      "benjy and quentin ",
      "second section",
    ],
    description: "",
  },
  {
    id: 8,
    book: "To The Lighthouse",
    author: "Virginia Woolf",
    cover: "https://images-na.ssl-images-amazon.com/images/I/51iWqn0jgdL._SX321_BO1,204,203,200_.jpg",
    tags: [],
    description: "",
  },
  {
    id: 9,
    book: "Pale Fire",
    author: "Vladimir Nabokov",
    cover: "https://m.media-amazon.com/images/I/91RaSXl-suL._AC_UL320_.jpg",
    tags: [],
    description: "",
  },
  {
    id: 10,
    book: "Anna Karenina*",
    author: "Leo Tolstoy",
    cover: "https://m.media-amazon.com/images/I/41iFiRIav7L.jpg",
    tags: [],
    description:
      "Anna Karenina (Russian: «Анна Каренина», IPA: [ˈanːə kɐˈrʲenʲɪnə])[1] is a novel by the Russian author Leo Tolstoy, first published in book form in 1878. Many writers consider Anna Karenina the greatest work of literature ever,[2] and Tolstoy himself called it his first true novel. It was initially released in serial installments from 1873 to 1877 in the periodical The Russian Messenger.",
  },
  {
    id: 11,
    book: "Madame Bovary*",
    author: "Gustave Flaubert",
    cover: "https://images-na.ssl-images-amazon.com/images/I/51fX6RpiYpL._SX331_BO1,204,203,200_.jpg",
    tags: [],
    description:
      "Madame Bovary (/ˈboʊvəri/;[1] French: [madam bɔvaʁi]), originally published as Madame Bovary: Provincial Manners (French: Madame Bovary: Mœurs de province [madam bɔvaʁi mœʁ(s) də pʁɔvɛ̃s]), is the debut novel of French writer Gustave Flaubert, published in 1856. The eponymous character lives beyond her means in order to escape the banalities and emptiness of provincial life.",
  },
  {
    id: 12,
    book: "War and Peace",
    author: "Leo Tolstoy",
    cover: "https://m.media-amazon.com/images/I/51K-U7lZIvL.jpg",
    tags: [],
    description: "",
  },
  {
    id: 13,
    book: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    cover: "https://m.media-amazon.com/images/I/51gUURA4FcL.jpg",
    tags: [],
    description: "",
  },
  {
    id: 14,
    book: "Middlemarch*",
    author: "George Eliot",
    cover: "https://m.media-amazon.com/images/I/515vob8r18L._SY346_.jpg",
    tags: [],
    description: "",
  },
  {
    id: 15,
    book: "Moby-Dick",
    author: "Herman Melville",
    cover: "https://images-na.ssl-images-amazon.com/images/I/416ZA21M6vL._SX331_BO1,204,203,200_.jpg",
    tags: [],
    description: "",
  },
  {
    id: 16,
    book: "Great Expectations*",
    author: "Charles Dickens",
    cover: "https://images-na.ssl-images-amazon.com/images/I/41XZpG3XjqL._SX331_BO1,204,203,200_.jpg",
    tags: [],
    description: "",
  },
  {
    id: 17,
    book: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    cover: "https://m.media-amazon.com/images/I/81qk21S0qVL._AC_UL320_.jpg",
    tags: [],
    description: "",
  },
  {
    id: 18,
    book: "Emma*",
    author: "Jane Austen",
    cover: "https://images-na.ssl-images-amazon.com/images/I/51nrg1To-kL._SX348_BO1,204,203,200_.jpg",
    tags: [],
    description:
      "First published at the end of 1815, Jane Austen’s “Emma” is the story of Emma Woodhouse, a young girl from a good home that does not need the financial support of a husband and is determined not to marry. Emma however is not opposed to the idea of marriage for others and is determined to play matchmaker between the local citizens. Greatly overestimating her own matchmaking abilities, the headstrong young girl is blind to the dangers of meddling in the affairs of others. When she confuses the attentions of Mr. Elton, the local vicar, as interest for her friend Harriet Smith, she briefly ruins the opportunity for Harriet to marry a respectable, educated, and well-spoken young farmer named Robert Martin. When Mr. Elton rejects the idea of being matched with Harriet, the girl is heartbroken, and Emma begins to realize that her actions although well-intended maybe doing more harm than good. In spite of Emma’s resolve not to marry she is presented with opportunities for romance throughout the book and eventually considers the prospect of marriage. “Emma,” a lively comedy of manners, is a classic story of 19th century romance and relationships. This edition includes an introduction by Austin Dobson and a biographical afterword.",
  },
];
