export default [
  {
    id: "1",
    country: "Austria",
    name: "Josef Bican ‡",
    goals: 805,
    status: "inactive",
    joined: "12/12/2019",
    description: `Puppy kitty ipsum dolor sit good dog foot stick canary. Teeth Mittens furry treats fish.`,
    link: "https://wegalvanize.com",
    shareable: true,
    level: "low",
    position: { id: 11, label: "striker" },
    hairColour: { id: 23, label: "grey" },
  },
  {
    id: "2",
    country: "Brazil",
    name: "Romário",
    goals: 772,
    status: "inactive",
    joined: "08/11/2019",
    description: `Puppy kitty ipsum dolor sit good dog foot stick canary. Teeth Mittens furry treats fish.`,
    link: "https://wegalvanize.com",
    shareable: false,
    level: "high",
    position: { id: 11, label: "striker" },
    hairColour: { id: 21, label: "black" },
  },
  {
    id: "3",
    country: "Brazil",
    name: "Pelé",
    goals: 767,
    status: "inactive",
    joined: "04/01/2014",
    description: `Puppy kitty ipsum dolor sit good dog foot stick canary. Teeth Mittens furry treats fish.`,
    link: "https://wegalvanize.com",
    shareable: true,
    level: "medium",
    position: { id: 12, label: "midfielder" },
    hairColour: { id: 21, label: "black" },
  },
  {
    id: "4",
    country: "Venezuela",
    name: "Lionel Messi",
    goals: 772,
    status: "active",
    joined: "01/01/2003",
    description: `Puppy kitty ipsum dolor sit good dog foot stick canary. Teeth Mittens furry treats fish.`,
    link: "https://wegalvanize.com",
    shareable: true,
    level: "high",
    position: { id: 13, label: "forward" },
    hairColour: { id: 22, label: "brown" },
  },
];
