export default function fixtures(times = 0) {
  const data = [
    [100000000000, "Austria", "Josef Bican ‡", 805, "inactive"],
    [2, "Brazil", "Romário", 772, "inactive"],
    [3, "Brazil", "Pelé", 767, "inactive"],
    [4, "Hungary", "Ferenc Puskás ‡	", 746, "inactive"],
    [5, "Germany", "Gerd Müller", 735, "inactive"],
    [6, "Portugal ", "Cristiano Ronaldo", 720, "active"],
    [7, "Argentina", "Lionel Messi	", 704, "active"],
    [8, "Hungary", "Ferenc Deák ‡", 576, "inactive"],
    [9, "Germany", "Uwe Seeler", 575, "inactive"],
    [9, "Brazil", "Túlio Maravilha	", 575, "inactive"],
    [11, "Brazil", "Arthur Friedenreich", 557, "inactive"],
    [12, "Poland", "Ernst Willimowski ‡", 554, "inactive"],
    [13, "Portugal", "Eusébio", 552, "inactive"],
    [14, "Scotland", "Jimmy McGrory", 550, "inactive"],
    [15, "Austria", "Franz Binder ‡", 546, "inactive"],
    [16, "Portugal ", "Fernando Peyroteo", 544, "inactive"],
    [17, "Sweden", "Zlatan Ibrahimović	", 543, "active"],
    [18, "Mexico", "Hugo Sánchez	", 541, "inactive"],
    [19, "Germany", "Fritz Walter ‡", 539, "inactive"],
    [20, "Hungary", "József Takács ‡	", 523, "inactive"],
    [21, "Hungary", "Gyula Zsengellér ‡	", 522, "inactive"],
    [21, "Brazil", "Zico", 522, "inactive"],
    [23, "Argentina", "Alfredo Di Stéfano ‡", 514, "inactive"],
    [23, "Austria", "Hans Krankl", 514, "inactive"],
    [25, "Sweden", "Gunnar Nordahl ‡", 513, "inactive"],
    [26, "Brazil", "Roberto Dinamite", 512, "inactive"],
    [27, "England", "Jimmy Greaves", 511, "inactive"],
    [28, "Hungary", "Ferenc Bene ‡", 508, "inactive"],
    [29, "Austria", "Josef Bican ‡", 805, "inactive"],
    [30, "Brazil", "Romário", 772, "inactive"],
    [31, "Brazil", "Pelé", 767, "inactive"],
    [32, "Hungary", "Ferenc Puskás ‡	", 746, "inactive"],
    [31, "Germany", "Gerd Müller", 735, "inactive"],
    [32, "Portugal ", "Cristiano Ronaldo", 720, "active"],
    [33, "Argentina", "Lionel Messi	", 704, "active"],
    [34, "Hungary", "Ferenc Deák ‡", 576, "inactive"],
    [35, "Germany", "Uwe Seeler", 575, "inactive"],
    [36, "Brazil", "Túlio Maravilha	", 575, "inactive"],
    [37, "Brazil", "Arthur Friedenreich", 557, "inactive"],
    [38, "Poland", "Ernst Willimowski ‡", 554, "inactive"],
    [39, "Portugal", "Eusébio", 552, "inactive"],
    [40, "Scotland", "Jimmy McGrory", 550, "inactive"],
    [41, "Austria", "Franz Binder ‡", 546, "inactive"],
    [42, "Portugal ", "Fernando Peyroteo", 544, "inactive"],
    [43, "Sweden", "Zlatan Ibrahimović	", 543, "active"],
    [44, "Mexico", "Hugo Sánchez	", 541, "inactive"],
    [45, "Germany", "Fritz Walter ‡", 539, "inactive"],
    [46, "Hungary", "József Takács ‡	", 523, "inactive"],
    [47, "Hungary", "Gyula Zsengellér ‡	", 522, "inactive"],
    [48, "Brazil", "Zico", 522, "inactive"],
    [49, "Argentina", "Alfredo Di Stéfano ‡", 514, "inactive"],
    [50, "Austria", "Hans Krankl", 514, "inactive"],
    [51, "Sweden", "Gunnar Nordahl ‡", 513, "inactive"],
    [52, "Brazil", "Roberto Dinamite", 512, "inactive"],
    [53, "England", "Jimmy Greaves", 511, "inactive"],
    [54, "Hungary", "Ferenc Bene ‡", 508, "inactive"],
  ];

  let newData = [];
  for (let i = 0; i < times; i++) {
    newData = newData.concat(data);
  }

  return times ? newData : data;
}
