const { getStoryUrlPrefix } = require("../../.storybook/storyTree");

const githubIssueBody = encodeURIComponent(`
# Help wanted

## Please write your question.
*A clear and concise description of what the question is*

## Additional context
*Add any other context or screenshots about your question here.*
`);

const readmeTemplate = ({
  displayName = "",
  name = "",
  description = "** require description **",
  content = "** require content **",
  props = "",
}) =>
  `
<!-- start: Autogenerated - do not modify -->

# ${name}

## Description
${description}

## Installation

\`\`\`
yarn add ${name}
\`\`\`

or with npm:

\`\`\`
npm install ${name}
\`\`\`

## Props 
${props}

<!-- end: Autogenerated - do not modify -->
${content}

## Links
- [Storybook Showcase](https://paprika.highbond.com/?path=/story/${getStoryUrlPrefix(displayName)}--showcase)
- [GitHub source code](https://github.com/acl-services/paprika/tree/master/packages/${displayName}/src)
- [Create GitHub issue](https://github.com/acl-services/paprika/issues/new?label=[]&title=${name}%20[help]:%20your%20short%20description&body=${githubIssueBody})
- [CHANGELOG](https://github.com/acl-services/paprika/tree/master/packages/${displayName}/CHANGELOG.md)
`;

module.exports = readmeTemplate;
