// Do not edit this file, it is automatically generated by @paprika/build-translations
  const locales = {
  "el": {
    "translation": {
      "formElement": {
        "optional": "(προαιρετικό)",
        "required": "(απαιτείται)"
      },
      "calendar": {
        "header_format": "MMMM YYYY",
        "month": "Μήνας",
        "year": "Έτος"
      },
      "actions": {
        "apply": "Εφαρμογή",
        "cancel": "Ακύρωση"
      }
    }
  }
};
  export default locales;