// Do not edit this file, it is automatically generated by @paprika/build-translations
  const locales = {
  "pl": {
    "translation": {
      "formElement": {
        "optional": "(opcjonalny)",
        "required": "(wymagane)"
      },
      "calendar": {
        "header_format": "MMMM YYYY",
        "month": "Miesiąc",
        "year": "Rok"
      },
      "actions": {
        "apply": "Zastosuj",
        "cancel": "Anuluj"
      }
    }
  }
};
  export default locales;