// Do not edit this file, it is automatically generated
const locales = {
  "pt": {
    "translation": {
      "moreInformation": "mais informações",
      "close": "Fechar",
      "uploader": {
        "overlay": {
          "title": "Arraste e solte",
          "subtitle": "Seus arquivos aqui"
        },
        "form": {
          "dragAndDrop": "Arraste e solte",
          "or": "ou",
          "chooseFiles": "Selecionar arquivos",
          "from": "Do seu computador"
        },
        "errors": {
          "file_size": "excede o tamanho máximo {{size}} do arquivo.",
          "file_type": "{{type}} é um tipo de arquivo incorreto."
        },
        "status": {
          "idle": "ocioso",
          "processing": "processando",
          "uploading": "fazendo upload",
          "success": "sucesso",
          "cancel": "cancelar",
          "error": "erro"
        }
      },
      "actions": {
        "delete": "Excluir",
        "apply": "Aplicar",
        "cancel": "Cancelar"
      },
      "dateInput": {
        "choose": "Escolha uma data",
        "clear": "Limpar Data"
      },
      "daterange": {
        "last_7_days": "Últimos 7 Dias",
        "last_30_days": "Últimos 30 Dias",
        "this_month": "Este Mês",
        "last_month": "Mês Passado",
        "start_date": "Data de Início",
        "end_date": "Data de Término"
      },
      "comment": {
        "delete": "Excluir comentário"
      },
      "pagination": {
        "intro": "Paginação, atualmente na página {{currentPage}}",
        "page": "Página {{pageNumber}}",
        "ellipsis": "Mais páginas",
        "prev": "Página anterior",
        "next": "Próxima página"
      },
      "formElement": {
        "optional": " (opcional)",
        "required": " (obrigatório)"
      },
      "prevNextArrowButton": {
        "arrowup": "para cima",
        "arrowdown": "para baixo",
        "escape": "ESC"
      },
      "externalLink": {
        "view": "exibir"
      },
      "collapsible": {
        "ariaText": "seção recolhível"
      }
    }
  }
};
export default locales;