// Do not edit this file, it is automatically generated by @paprika/build-translations
  const locales = {
  "ro": {
    "translation": {
      "formElement": {
        "optional": "(opțional)",
        "required": "(obligatoriu)"
      },
      "calendar": {
        "header_format": "MMMM YYYY",
        "month": "Lună",
        "year": "An"
      },
      "actions": {
        "apply": "Aplică",
        "cancel": "Anulare"
      }
    }
  }
};
  export default locales;