// Do not edit this file, it is automatically generated by @paprika/build-translations
  const locales = {
  "ru": {
    "translation": {
      "formElement": {
        "optional": "(опционально)",
        "required": "(обязательно)"
      },
      "calendar": {
        "header_format": "MMMM YYYY",
        "month": "Месяц",
        "year": "Год"
      },
      "actions": {
        "apply": "Применить",
        "cancel": "Отмена"
      }
    }
  }
};
  export default locales;