// Do not edit this file, it is automatically generated by @paprika/build-translations
  const locales = {
  "uk": {
    "translation": {
      "formElement": {
        "optional": "(за бажанням)",
        "required": "(обов’язково)"
      },
      "calendar": {
        "header_format": "MMMM YYYY",
        "month": "Місяць",
        "year": "Рік"
      },
      "actions": {
        "apply": "Застосувати",
        "cancel": "Скасувати"
      }
    }
  }
};
  export default locales;