export default [
  {
    id: "1",
    country: "Austria",
    name: "Josef Bican ‡",
    goals: 805,
    status: "inactive",
    joined: "12/12/2019",
    description: `Puppy kitty ipsum dolor sit good dog foot stick canary. Teeth Mittens furry treats fish.`,
    link: "https://wegalvanize.com",
    shareable: true,
    level: "low",
  },
  {
    id: "2",
    country: "Brazil",
    name: "Romário",
    goals: 772,
    status: "inactive",
    joined: "08/11/2019",
    description: `Puppy kitty ipsum dolor sit good dog foot stick canary. Teeth Mittens furry treats fish.`,
    link: "https://wegalvanize.com",
    shareable: false,
    level: "high",
  },
  {
    id: "3",
    country: "Brazil",
    name: "Pelé",
    goals: 767,
    status: "inactive",
    joined: "04/01/2014",
    description: `Puppy kitty ipsum dolor sit good dog foot stick canary. Teeth Mittens furry treats fish.`,
    link: "https://wegalvanize.com",
    shareable: true,
    level: "mid",
  },
];
