import fs from "fs";
import path from "path";
import jsYaml from "js-yaml";

const buildPath = output => path.resolve(process.cwd(), output);

const isJsTranslationFile = fileName => fileName.split(".")[1] === "js" && fileName.split(".")[0] !== "index";

const removeTranslationFiles = outputPath => {
  fs.readdir(buildPath(outputPath), (err, files) => {
    if (err) {
      return console.error("Couldnt scan directory");
    }

    files.forEach(fileName => {
      if (fileName !== ".gitkeep" && isJsTranslationFile(fileName)) {
        fs.unlinkSync(buildPath(`${outputPath}/${fileName}`));
      }
    });
  });
};

export default function buildTranslations({
  sourcePath = process.cwd(),
  outputPath = sourcePath,
  yamlFileExtension = "yml",
}) {
  const isYamlFile = fileName => fileName.split(".")[1] === yamlFileExtension;
  const createTranslationFile = yamlFileName => {
    const outputFileName = yamlFileName.replace(`.${yamlFileExtension}`, ".js");
    const yamlAsJsonObject = jsYaml.load(
      fs.readFileSync(buildPath(`${sourcePath}/${yamlFileName}`), { encoding: "utf-8" })
    );
    const outputFileContents = `// Do not edit this file, it is automatically generated by @paprika/build-translations
    const locales = ${JSON.stringify(yamlAsJsonObject, null, 2)};
    export default locales;`;
    fs.writeFile(buildPath(`${outputPath}/${outputFileName}`), outputFileContents, () => {});
  };
  const generateTranslationFiles = () => {
    fs.readdir(buildPath(sourcePath), (err, yamlFiles) => {
      if (err) {
        console.log(err);
        console.error("Couldn't scan directory");
        process.exit(1);
      }

      yamlFiles.forEach(yamlFileName => {
        if (isYamlFile(yamlFileName)) {
          createTranslationFile(yamlFileName);
        }
      });
    });
  };

  try {
    removeTranslationFiles(outputPath);
    generateTranslationFiles();
  } catch (e) {
    console.error(e);
  }
}
